import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { useContext, useState } from "react";
import { GeneralContext } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export default function Dashbord() {
  const {
    handlePacthContact,
    handleDeleteContact,
    handlePacthUser,
    handleDeleteUser,
    handleAddContact,
    handleExit,
    user,
    loading,
  } = useContext(GeneralContext);
  const [open, setOpen] = useState(false);
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  const [idContat, setIdContat] = useState("");

  return (
    <>
      <Head>
        <title>Agenda Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full items-center justify-around gap-20 h-[100vh] bg-[#119DA4]">
        <main className=" rounded-md w-35% h-40% flex items-center justify-center flex-col gap-5 bg-gray-800 max-w[80%] p-8 sm:p-20">
          {!loading && (
            <>
              <h2 className="text-white sm:text-3xl font-bold text-center text-xl" >Ola {user.name}</h2>
              <button
                onClick={() => {
                  setOpen(!open);
                }}
                className="bg-gray-600 sm:text-3xl text-xl text-white p-2 rounded-md hover:bg-gray-700 buttons"
              >
                Editar
              </button>

              <button
                onClick={() => {
                  handleExit();
                }}
                className="bg-gray-600 sm:text-3xl text-xl text-white p-2 rounded-md hover:bg-gray-700 buttons"
              >
                Sair
              </button>

              <h2 className="text-white font-bold sm:text-3xl text-xl">Seus contatos</h2>
              <div className="flex w-[50vw] min-w-[250px]  items-start overflow-x-auto tess">
                {user.contacts.map((contact) => {
                  return (
                    <div className="w-64 h-64 p-5 rounded-lg bg-white m-5 flex flex-col justify-between">
                      <p className="text-indigo-700 font-bold">
                        Nome: {contact.name}
                      </p>
                      <p className="text-indigo-700 font-bold">
                        Número: {contact.phone}
                      </p>
                      <div className="mt-5">
                        <button
                          onClick={() => handleDeleteContact(contact.id)}
                          className="bg-indigo-700 text-white rounded-md py-2 px-4  w-[100%] mb-3 buttons"
                        >
                          Remover
                        </button>
                        <button
                          onClick={() => {
                            setOpen2(!open2);
                            setIdContat(contact.id);
                          }}
                          className="bg-indigo-700 text-white rounded-md py-2 px-4 w-[100%] mb-3 buttons"
                        >
                          Editar
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>

              <button
                onClick={() => setOpen3(true)}
                className="bg-gray-600 text-white min-w-min p-2 rounded-md hover:bg-gray-700 mt-2 sm:text-3xl text-xl buttons"
              >
                Adicionar contato
              </button>
            </>
          )}
        </main>

      
      </div>

      {open && (
          <div className="fixed bottom-0 inset-x-0 px-4 pb-4 inset-0 flex items-center justify-center">
            <div className="fixed inset-0 transition-opacity">
              <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <div
              className="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full"
              role="dialog"
              aria-modal="true"
              aria-labelledby="modal-headline"
            >
              <div className="bg-[#119DA4] p-5">
                <h2 className="text-white text-lg font-medium">
                  Editar usuário
                </h2>
              </div>
              <form
                className="px-10 py-10"
                onSubmit={(e) => {
                  e.preventDefault();
                  handlePacthUser(
                    {
                      name: name ? name : undefined,
                      password: password ? password : undefined,
                      email: email ? email : undefined,
                      phone: phone ? phone : undefined,
                    },
                    setOpen
                  );

                  setName("");
                  setPassword("");
                  setEmail("");
                  setPhone("");
                }}
              >
                <input
                  className="w-full p-2 border border-gray-400 rounded-lg"
                  placeholder="Nome"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Senha"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  type="password"
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Número"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                ></input>
                <button
                  className="bg-[#119DA4] text-white w-full p-2 mt-5 rounded-lg hover:brightness-75 buttons"
                  type="submit"
                >
                  Alterar
                </button>
                <button
                  className="bg-red-500 text-white w-full p-2 mt-5 rounded-lg hover:brightness-75 buttons"
                  onClick={() => handleDeleteUser()}
                >
                  Excluir
                </button>
              </form>
              <button
                className="fixed top-4 right-4 cursor-pointer border-none w-auto h-auto text-2xl text-white"
                onClick={() => setOpen(false)}
              >
                ×
              </button>
            </div>
          </div>
        )}

        {open2 && (
          <div className="fixed bottom-0 inset-x-0 px-4 pb-4 inset-0 flex items-center justify-center">
            <div className="fixed inset-0 transition-opacity">
              <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <div
              className="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full"
              role="dialog"
              aria-modal="true"
              aria-labelledby="modal-headline"
            >
              <div className="bg-[#119DA4] p-5">
                <h2 className="text-white text-lg font-medium">
                  Altere os dados
                </h2>
              </div>
              <form
                className="px-10 py-10"
                onSubmit={(e) => {
                  e.preventDefault();
                  handlePacthContact(
                    {
                      name: name ? name : undefined,
                      phone: phone ? phone : undefined,
                    },
                    idContat,
                    setOpen2
                  );
                  setName("");
                  setPassword("");
                  setEmail("");
                  setPhone("");
                }}
              >
                <input
                  className="w-full p-2 border border-gray-400 rounded-lg"
                  placeholder="Nome"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Número"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                ></input>
                <button
                  className="bg-[#119DA4] text-white w-full p-2 mt-5 rounded-lg hover:brightness-75 buttons"
                  type="submit"
                >
                  Alterar
                </button>
              </form>
              <button
                className="fixed top-4 right-4 cursor-pointer border-none w-auto h-auto  text-2xl text-white"
                onClick={() => setOpen2(false)}
              >
                ×
              </button>
            </div>
          </div>
        )}

        {open3 && (
          <div className="fixed bottom-0 inset-x-0 px-4 pb-4 inset-0 flex items-center justify-center">
            <div className="fixed inset-0 transition-opacity">
              <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <div
              className="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full"
              role="dialog"
              aria-modal="true"
              aria-labelledby="modal-headline"
            >
              <div className="bg-[#119DA4] p-5">
                <h2 className="text-white text-lg font-medium">
                  Adicionar contato
                </h2>
              </div>
              <form
                className="px-10 py-10"
                onSubmit={(e) => {
                  e.preventDefault();
                  handleAddContact(
                    {
                      name: name ? name : undefined,
                      phone: phone ? phone : undefined,
                      email: email ? email : undefined,
                      userId: user.id,
                    },
                    setOpen3
                  );
                  setName("");
                  setPassword("");
                  setEmail("");
                  setPhone("");
                }}
              >
                <input
                  className="w-full p-2 border border-gray-400 rounded-lg"
                  placeholder="Nome"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                ></input>
                <input
                  className="w-full p-2 mt-5 border border-gray-400 rounded-lg"
                  placeholder="Número"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  required
                ></input>
                <button
                  className="bg-[#119DA4] text-white w-full p-2 mt-5 rounded-lg hover:brightness-75 buttons"
                  type="submit"
                >
                  Adicionar
                </button>
              </form>
              <button
                className="fixed top-4 right-4 cursor-pointer border-none w-auto h-auto text-2xl text-white"
                onClick={() => setOpen3(false)}
              >
                ×
              </button>
            </div>
          </div>
        )}
    </>
  );
}
