import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Register() {

    return (
        <>
        <Head>
            <title>Agenda Online</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex w-full items-center justify-around gap-20 h-[100vh] bg-[#119DA4]'>
            <main className=' p-20 rounded-md  w-[35%] h-auto flex items-center justify-center flex-col gap-5 bg-[#13505B]'>
            <h2 className="text-white text-3xl font-bold">Cadastre-se</h2>
            <input placeholder='Nome completo' required/>
            <input placeholder='Email' required/>
            <input placeholder='Senha' required/>
            <input placeholder='Telephone' required/>
            <Link href={"/login"}>Cadastrar-se</Link>
            </main>
        </div>

        </>
    )
}
